downsample_resolution: 0.02 # Meters

# These settings are for the static sample point cloud (which is misaligned)
crop_box_min: {x: -2, y: -2, z: -2} # Meters
crop_box_max: {x: 2, y: 1, z: 2} # Meters

# These settings are for Gazebo
#crop_box_min: {x: -3, y: -3, z: -3} # Meters
#crop_box_max: {x: 3, y: 3, z: 3} # Meters

outlier_removal: {
  mean_k: 50,
  stddev: 3.0
}

normals_estimation: {
  search_radius: 0.15, # TODO: Units
  gaussian_parameter: 0.15,
}

region_segmentation: {
  min_cluster_size: 200, # Points per cluster
  smooth_mode: false # Don't allow regions to grow around corners
}

sac_segmentation: {
  model_type: 0, # 0 = Plane
  method_type: 0, # 0 = RANSAC
  distance_threshold: 0.1, # Meters (I think)
}

concave_hull: {
  alpha: 0.05
}