downsample_resolution: 0.01 # Meters

target_frame: "/world"

parallel_distance_threshold: 0.15 # Meters (I think)
expansion_distance_threshold: 0.15 # Meters (I think)
perpendicular_distance_threshold: 0.02 # Meters (I think)

# These settings are for the static sample point cloud (which is misaligned)
#crop_box_min: {x: -2, y: -2, z: -2} # Meters
#crop_box_max: {x: 2, y: 1, z: 2} # Meters

# These settings are for the timed point cloud
#crop_box_min: {x: -10, y: -2, z: -10} # Meters
#crop_box_max: {x: 10, y: 1, z: 10} # Meters

# These settings are for Gazebo
crop_box_min: {x: -5, y: -5, z: -5} # Meters
crop_box_max: {x: 5, y: 5, z: 5} # Meters

outlier_removal: {
  mean_k: 50,
  stddev: 3.0
}

normals_estimation: {
  search_radius: 0.15, # TODO: Units
  gaussian_parameter: 0.15
}

region_segmentation: {
  min_cluster_size: 500, # Points per cluster
  smooth_mode: false, # Don't allow regions to grow around corners
  smoothness_threshold: deg(30),
  curvature_threshold: 0.03
}

sac_segmentation: {
  model_type: 0, # 0 = Plane
  method_type: 0, # 0 = RANSAC
}