downsample_resolution: 0.02 # Meters

crop_box_min: {x: -3, y: -2, z: -3} # Meters
crop_box_max: {x: 3, y: 1, z: 3} # Meters

outlier_removal: {
  mean_k: 50,
  stddev: 3.0
}

normals_estimation: {
  search_radius: 0.15, # TODO: Units
  gaussian_parameter: 0.15,
}

region_segmentation: {
  min_cluster_size: 100, # Points per cluster
  smooth_mode: false # Don't allow regions to grow around corners
}

sac_segmentation: {
  model_type: 0, # 0 = Plane
  method_type: 0, # 0 = RANSAC
  distance_threshold: 0.02, # TODO: Units
}